[package]
name = "cel-parser"
description = "A parser for the Common Expression Language (CEL)"
repository = "https://github.com/orf/cel-rust"
version = "0.3.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
license = "MIT"
categories = ["parsing", "cel"]

[dependencies]
lalrpop-util = { version = "0.19.1", features = ["lexer"] }
regex = "1.4.2"

[build-dependencies]
lalrpop = { version = "0.19.1", features = ["lexer"] }
