[package]
name = "cel-interpreter"
description = "An interpreter for the Common Expression Language (CEL)"
repository = "https://github.com/orf/cel-rust"
version = "0.1.1-alpha.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
license = "MIT"
categories = ["interpreter", "cel"]

[dependencies]
cel-parser = {version="0.1.1-alpha.0", path="../parser"}
thiserror = "1.0.22"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "runtime"
harness = false
